### ISSUE TITLE
Support using Ceylon collections in multi-value fields

### ISSUE THREAD

**Issue by CPColin** [CPColin/ceylon-spring-experiments#10]
The `User` and `Role` classes each have fields annotated `manyToMany`. These fields use `java.util` collections, because Hibernate (and Spring?) does not know how to handle Ceylon collections by default. We should see if we can make a converter for `ceylon.lang::List` (or even `ceylon.lang::Iterable`).

**Comment by gavinking** [comment]
It's Hibernate's fault. And when I investigated this it wasn't trivial to change Hibernate to support Ceylon collections. (But it's not impossible either.)

**Comment by gavinking** [comment]
Ooops, I forgot about 

<https://ceylon-lang.org/documentation/1.3/reference/interoperability/ee-mode/#java_types_for_list_set_and_map>

**Comment by CPColin** [comment]
Thanks! Swapped out a couple of `{T*}` uses for `Set<T>` and updated my README to clarify.

**Comment by gavinking** [comment]
Cool!
